//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppFaculty
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTNO
    {
        public int ID { get; set; }
        public Nullable<int> STD_ID { get; set; }
        public System.DateTime REGIS_DATE { get; set; }
        public string PRIM_NUM { get; set; }
        public string SECON_NUM { get; set; }
        public string SMS_NUM { get; set; }
        public string OTHER_NUM { get; set; }
    }
}
