//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppFaculty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APTECHDBEntities : DbContext
    {
        public APTECHDBEntities()
            : base("name=APTECHDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACADMIC> ACADMICS { get; set; }
        public virtual DbSet<APPROGRAM> APPROGRAMs { get; set; }
        public virtual DbSet<ATTENDANCE> ATTENDANCEs { get; set; }
        public virtual DbSet<BATCH_REGISTRATION> BATCH_REGISTRATION { get; set; }
        public virtual DbSet<BATCHDAY> BATCHDAYS { get; set; }
        public virtual DbSet<CONTACTNO> CONTACTNOes { get; set; }
        public virtual DbSet<COURS> COURSES { get; set; }
        public virtual DbSet<FACULTY> FACULTies { get; set; }
        public virtual DbSet<FACUTLY_BATCH> FACUTLY_BATCH { get; set; }
        public virtual DbSet<REGSKILL> REGSKILLs { get; set; }
        public virtual DbSet<SEMESTER> SEMESTERS { get; set; }
        public virtual DbSet<SKILL> SKILLS { get; set; }
        public virtual DbSet<STUDENTINFO> STUDENTINFOes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USEROLE> USEROLEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<VMBACTH_FA> VMBACTH_FA { get; set; }
    }
}
